package io.github.hapjava.characteristics.impl.common;

import io.github.hapjava.characteristics.HomekitCharacteristicChangeCallback;
import io.github.hapjava.characteristics.impl.base.EnumCharacteristic;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * This characteristic describes an event generated by a programmable switch. Reading this
 * characteristic must return the last event triggered for BLE. For IP accessories, the accessory
 * must set the value of Paired Read to null(i.e. ”value” : null) in the attribute database. A read
 * of this characteristic must always return a null value for IP accessories. The value must only be
 * reported in the events (”ev”) property..
 *
 * @author Eugen Freiter
 */
public class ProgrammableSwitchEventCharacteristic
    extends EnumCharacteristic<ProgrammableSwitchEnum> {

  public ProgrammableSwitchEventCharacteristic(
      Supplier<CompletableFuture<ProgrammableSwitchEnum>> getter,
      Consumer<HomekitCharacteristicChangeCallback> subscriber,
      Runnable unsubscriber) {
    super(
        "00000073-0000-1000-8000-0026BB765291",
        "Switch Event",
        2,
        Optional.of(getter),
        Optional.empty(),
        Optional.of(subscriber),
        Optional.of(unsubscriber));
  }
}
